---
title: How To Move To
timezone: UTC
collections:
  guides:
    title: Guides
    output: true
    in_nav: 1
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
permalink: pretty
