---
title: How To Move To
url: http://howtomove.to
timezone: UTC
collections:
  "-guides-us":
    title: From The United States
    output: true
  guides:
    title: Guides
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
permalink: pretty
